# -*- coding: utf-8 -*-
"""grad_cam_router.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3DSLXgZGKRYuSA40HP3ks0zT131NATA
"""

!git clone https://github.com/Saumi18/Signal-Sight.git

import torch
import torch.nn as nn
import numpy as np
import os
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# import sys

# # Add the directory containing your python file to the system path
# sys.path.append('/content/Signal-Slight/')

# from models.routercnn import RouterCNN

import sys

# Add the directory containing your python file to the system path
sys.path.append('/content/Signal-Sight/routerCnn.py')

from routerCnn import RouterCNN
model = RouterCNN(num_classes=4).to("cuda")

activations = None   # will store forward feature maps
grads = None         # will store backward gradients

def forward_hook(module, input, output):
    # Save feature maps (activations) from chosen layer
    # Shape: [B, C, H, W]
    global activations
    activations = output.detach()

def backward_hook(module, grad_input, grad_output):
    # Save gradients wrt activations
    # grad_output[0] has shape [B, C, H, W]
    global grads
    grads = grad_output[0].detach()

model.conv[8].registered_forward_hook(forward_hook)
model.conv[8].registered_forward_hook(backward_hook)
spec= '/content/Signal-Sight/spectrogram_extract.py'
spec= np.expand_dims(spec, axis=0)  # add channel dim
spec = torch.tensor(spec, dtype=torch.float32).unsqueeze(0).to(device)

#logits = model(spec)

# ---------------------------
# input spectrogram
#inputs = inputs.to(device)

# forward pass through RouterCNN
logits = model(spec)   # logits = raw outputs (tensor)

target_class = logits.argmax(dim=1).item() # family index for Router
score = logits[0, target_class]

model.zero_grad()
score.backward()

weights = grads.mean(dim=(2, 3))[0]   # Shape: [C]

# Weighted sum of activations
cam = torch.zeros(activations.shape[2:], dtype=torch.float32).to(device)  # [H, W]
for c, w in enumerate(weights):
    cam += w * activations[0, c, :, :]   # weighted feature map

cam -= cam.min()
cam /= cam.max()

# Resize CAM to match input spectrogram size
cam = torch.nn.functional.interpolate(
    cam.unsqueeze(0).unsqueeze(0),  # [1,1,H,W]
    size=spec.shape[2:],             # match input [H_input, W_input]
    mode='bilinear',
    align_corners=False
)
cam = cam.squeeze().cpu().numpy()  # final CAM: 2D heatmap

import matplotlib.pyplot as plt

plt.imshow(spec.squeeze().cpu().numpy(), cmap='gray')
plt.imshow(cam, cmap='jet', alpha=0.4)  # overlay
plt.colorbar()
plt.show()